<?php

define('SORT_COMMENTS_OLDER_FIRST', 1); // default
define('SORT_COMMENTS_NEWER_FIRST', 2);

/**
 * Implements hook_help().
 */
function inline_comments_help($path) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#inline_comments":
      $output = '<p>' . t("Inline comments is a view handler let you display  and make comments inline via ajax.") . '</p>';
      break;
  }
  return $output;
}


/**
 * Implements hook_views_api().
 */
function inline_comments_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'inline_comments') . '/inc',
  );
}


/**
  * Implements hook_menu().
  */

function inline_comments_menu() {
  $items['ajax/inline_comments/add_comments'] = array(
    'title' => 'Add Inline Comments',
    'type' => MENU_CALLBACK,
    'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_add_comments',
    'access arguments' => array('post comments'),
  );

  $items['ajax/inline_comments/get_comments/%'] = array(
    'title' => 'Get Inline Comments',
    'type' => MENU_CALLBACK,
    'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_get_comments',
    'access arguments' => array('access comments'),
  );
  $items['ajax/inline_comments/get_comment_form/%'] = array(
    'title' => 'Get Inline Comments',
    'type' => MENU_CALLBACK,
    'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_get_comment_form',
    'access arguments' => array('access comments'),
  );
  return $items;
}


function inline_comments_preprocess_comment(&$vars) {
  $vars['title'] = ''; //set to empty string instead of unset to avoid warnings on node pages
  $vars['submitted'] = t('!username !datetime', array('!username' => $vars['author'], '!datetime' => $vars['created']));

}


function inline_comments_query_alter(QueryAlterableInterface $query) {
  if ( ($node = $query->getMetaData('node')) && (get_class($query) == 'PagerDefault') ) {
    $sort = variable_get('comment_default_sorting_' . $node->type, SORT_COMMENTS_NEWER_FIRST);
      if ($sort == SORT_COMMENTS_NEWER_FIRST) {
      $orderby =& $query->getOrderBy();  
      $expressions =& $query->getExpressions();
      if (isset($orderby['torder'])) { 
          unset($expressions['torder']);
          unset($orderby['torder']);
          $orderby['c.thread'] = 'DESC';
      } else {
        $orderby['c.cid'] = 'DESC';
      }
    }
  }
}

function inline_comments_theme_registry_alter(&$theme_registry) {
  // using our own comment.tpl.php file.
  $theme_registry['comment']['template'] = 'comment';
  $theme_registry['comment']['path'] = drupal_get_path('module', 'inline_comments');
  $theme_registry['comment']['type'] = 'module';
  $theme_registry['comment']['theme path'] = drupal_get_path('module', 'inline_comments');
  $theme_registry['comment']['theme paths'] = Array();
}