<?php

/**
 * @file
 *
 *  change page title for user  pages 
 */

  
/**
 * @file
 *
 *  implement hook_form_alter()for customize user pages 
 */


function lxpt_og_form_alter(&$form,&$form_state,$form_id){
 switch ($form_id){ 
	case'comment_node_posts_form':
        $form['author']['_author']['#title'] = t('姓名');
		$form['author']['name']['#title'] = t('姓名');
		$form['author']['name']['#maxlength'] = 15;
		$form['author']['name']['#size'] = 15;
		
		//$form['subject']['#title'] = t('评论标题');
		$form['actions']['submit']['#value'] = t('确认');
		unset($form['subject']);
		unset($form['comment_body']['und'][0]['#title']);
		unset($form['comment_body']['und'][0]['#required']);
		hide($form['actions']['preview']);
		break;
		
		
	}	
 
//dsm($form);

return $form;
}

/**
 * Implements hook_menu_alter().
 *
 * 
 **/

 function lxpt_og_menu_link_alter(&$items) {
  /* 
  *Hiden  menu tabs for user pages
  
  */
  //dsm($items['links__comment']);
  
   
}


function lxpt_og_comment_view_alter(&$build) {
  // Check for the existence of a field added by another module.
  if ($build['#view_mode'] == 'full' && isset($build['links'])) {
    //dsm ($build['links']);
    // Change its weight.
    $build['links']['comment']['#links']['comment-reply']['title'] =t('回复') ;
  }

  // Add a #post_render callback to act on the rendered HTML of the comment.
  $build['#post_render'][] = 'lxpt_og_comment_post_render';
}













